import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { FiGithub } from "react-icons/fi";
import { FiExternalLink } from "react-icons/fi";
import Image from 'next/image';
import deved from '../public/dev-flor.png';
import front from '../public/front-end.png';
import server from '../public/data-center.png';
import soft from '../public/soft-skills.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ''}>
      <Head>
        <title>Florencia Belén Mussis Portfolio</title>
        <meta name='description' content='Generated by cre'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons dark:text-gray-400'>developedbyflor</h1>
            <ul className='flex items-center'>
              <li className='dark:text-white'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8' href='https://drive.google.com/file/d/1l-WT4dbyV2_pSnd7zP-MN6fKBTzIGsOE/view?usp=sharing'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl'>Florencia Belén Mussis</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200'>Desarrolladora web habituada al trabajo en equipo<br /> y con habilidades comunicativas.<br />
              Conocimientos en desarrollo web front-end con HTML, CSS, JavaScript y Single Page Application utilizando framework React.<br /> Conocimientos de desarrollo cliente-servidor con <br /> Node.js, Express.js, MongoDB y Mongoose.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <a href='https://www.linkedin.com/in/florencia-mussis'><AiFillLinkedin /></a>
            <a href='https://github.com/Florencia-Mussis'><AiFillGithub /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} object-fit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl pb-1 mt-20 dark:text-white'>Habilidades</h3>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={front} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>FRONT END</h3>
              <p className='py-2'>Para el desarrollo de la interfaz de un sitio web, desde su estructura hasta los estilos, estoy habituada a trabajar con:</p>
              <p className='text-teal-600 py-1'>Html</p>
              <p className='text-teal-600 py-1'>Css</p>
              <p className='text-teal-600 py-1'>Bootstrap</p>
              <p className='text-teal-600 py-1'>Tailwind</p>
              <p className='text-teal-600 py-1'>JavaScript</p>
              <p className='text-teal-600 py-1'>React.js</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={server} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>BACK END</h3>
              <p className='py-2'>Para el desarrollo del lado del servidor y utilizando bases de datos tengo experiencia con:</p>
              <p className='text-teal-600 py-1'>Node.js</p>
              <p className='text-teal-600 py-1'>Express.js</p>
              <p className='text-teal-600 py-1'>MongoDB</p>
              <p className='text-teal-600 py-1'>Mongoose</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={soft} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>SOFT SKILLS</h3>
              <p className='py-2'>De mis competencias personales que me permiten desempeñarme en un trabajo de manera efectiva destaco:</p>
              <p className='text-teal-600 py-1'>Perseverancia</p>
              <p className='text-teal-600 py-1'>Trabajo en equipo</p>
              <p className='text-teal-600 py-1'>Atención al detalle</p>
              <p className='text-teal-600 py-1'>Adaptabilidad</p>
              <p className='text-teal-600 py-1'>Saber priorizar</p>
              <p className='text-teal-600 py-1'>Capacidad multitasking</p>
            </div>
          </div>
        </section>
        <section className='py-10'>
          <div>
            <h3 className='text-3xl pb-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>Desarrollos web que he realizado desde cero. </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <a className='text-2xl flex justify-center gap-16 py-3 mt-3 text-gray-600 dark:text-gray-400' href='https://mind-free.surge.sh/'><FiExternalLink /></a>
              <div className='text-xs px-2 justify-center gap-2  text-gray-600 dark:text-gray-400'>
                <p> Usuario de prueba: sara@gmail.com</p>
                <p> Contraseña: 123123123</p>
              </div>
            </div>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <div className='flex justify-center gap-4'>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/Florencia-Mussis/Portfolio'><FiGithub /></a>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://florencia-mussis.github.io/Portfolio/'><FiExternalLink /></a>
              </div>
            </div>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://pokedex-pokeapi-react-typescript.netlify.app/'><FiExternalLink /></a>
            </div>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <div className='flex justify-center gap-4'>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/Florencia-Mussis/minimalist-website'><FiGithub /></a>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://florencia-mussis.github.io/minimalist-website/'><FiExternalLink /></a>
              </div>
            </div>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <div className='flex justify-center gap-4'>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://github.com/Florencia-Mussis/Coderhouse-Proyecto-final'><FiGithub /></a>
                <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://florencia-mussis.github.io/Coderhouse-Proyecto-final/'><FiExternalLink /></a>
              </div>
            </div>
            <div className='basis-1/3 flex-1 border rounded-md border-gray-300'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} />
              <a className='text-2xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400' href='https://www.figma.com/proto/jVemOixIxblL1W3PfsnuYI/My-Lists?node-id=1-2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2'><FiExternalLink/></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
